apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ov81iv75t-java-quarkus
  janus-idp.io/tekton: ov81iv75t-java-quarkus
  backstage.io/kubernetes-id: ov81iv75t-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ov81iv75t-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
